# Generated by Django 4.0.5 on 2022-07-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_imagine_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
