# Generated by Django 4.0.5 on 2022-07-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBorder',
        ),
    ]
