# Generated by Django 4.0.5 on 2022-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_zip_code_order_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cap',
            field=models.IntegerField(),
        ),
    ]
