# Generated by Django 4.0.5 on 2022-07-01 18:12

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
