# Generated by Django 4.0.5 on 2022-07-01 20:01

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('orders', '0004_order_geolocation_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
