# Generated by Django 4.0.5 on 2022-07-04 13:12

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.mylocationmodel'),
        ),
    ]
