# Generated by Django 4.0.5 on 2022-07-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
